version: '3'

volumes:
  pg_data:
  static:
  uploads:

services:
  db:
    image: postgres:13
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file: .env
  backend:
    image: iceberen/kittygram_backend
    env_file: .env
    volumes:
      - static:/static
      - uploads:/uploads
    depends_on:
      - db
  frontend:
    env_file: .env
    image: iceberen/kittygram_frontend
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static
  gateway:
    image: iceberen/kittygram_gateway
    env_file: .env
    ports:
      - 9000:80
    volumes:
      - static:/static
      - uploads:/uploads